'use strict';

const CONSTANTS = {};

CONSTANTS.SERVER = {
	ONE: 1,
};

CONSTANTS.ERROR_TYPES = {
	DATA_NOT_FOUND: 'DATA_NOT_FOUND',
	BAD_REQUEST: 'BAD_REQUEST',
	MONGO_EXCEPTION: 'MONGO_EXCEPTION',
	ALREADY_EXISTS: 'ALREADY_EXISTS',
	FORBIDDEN: 'FORBIDDEN',
	INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
	TOO_MANY_REQUESTS: 'TOO_MANY_REQUESTS',
	UNAUTHORIZED: 'UNAUTHORIZED',
	INVALID_MOVE: 'InvalidMove',
};

CONSTANTS.TX_TOPIC_TYPE = {
	GOLD_BAR_SOLD: '0x5d877c43feb4a1b48a28396a2ab51b4f61c97f92bdd6e10ee923e2d239e4d10b',
	TRANSFER: '0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef',
};


CONSTANTS.REFERRAL_CODE_LENGTH = 6;

CONSTANTS.SERVER_TYPES = {
	API: 'api',
	SOCKET: 'socket',
};

CONSTANTS.USER_ROLES = {
	ADMIN: 1,
};

CONSTANTS.AVAILABLE_AUTHS = {
	ADMIN: 1,
	USER: 2,
};

CONSTANTS.FILE_UPLOAD_TYPE = {
	PROFILE_IMAGE: 1,
};

CONSTANTS.TOKEN_TYPES = {
	LOGIN: 1,
	OTP: 2,
	RESET_PASSWORD: 3,
};

CONSTANTS.OTP_TYPES = {
	EMAIL_VERIFICATION: 1,
	FORGOT_PASSWORD: 2,
};

CONSTANTS.DATABASE_VERSIONS = {
	ONE: 1,
	TWO: 2,
	THREE: 3,
	FOUR: 4,
	FIVE: 5,
};

CONSTANTS.USER_TYPE = {
	ADMIN: 1,
};

CONSTANTS.PASSWORD_PATTER_REGEX = /^(?=.{6,})(?=.*[a-z])(?=.*[0-9])(?=.*[A-Z])(?=.*[@#$%^&+=]).*$/;

CONSTANTS.NAME_REGEX = /^[a-zA-Z\s]{1,20}[a-zA-Z\s]$/;
CONSTANTS.PHONE_REGEX = /^\+\d{1,3}\d{8,10}$/;
CONSTANTS.ETHEREUM_ADDRESS_REGEX = /^0x[a-fA-F0-9]{40}$/;

CONSTANTS.NORMAL_PROJECTION = {
	__v: 0, isDeleted: 0, createdAt: 0, updatedAt: 0,
};

CONSTANTS.MESSAGES = require('./messages');

CONSTANTS.SECURITY = {
	JWT_SIGN_KEY: 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads',
	BCRYPT_SALT: 8,
	STATIC_TOKEN_FOR_AUTHORIZATION: '58dde3df315587b279edc3f5eeb98145',
};
CONSTANTS.MAP_DEFAULT_MONGO_ID = '6298bbf1c5f9f220b1dd1de2';

CONSTANTS.LOGIN_TYPES = {
	METAMASK: 1,
};

CONSTANTS.EMAIL_TYPES = {
	RESET_PASSWORD_EMAIL: 1,
	EMAIL_VERIFICATION: 2,
	SETUP_PASSWORD: 3,
};
  
CONSTANTS.EMAIL_SUBJECTS = {
	RESET_PASSWORD_EMAIL: 'Reset Password',
	EMAIL_VERIFICATION: 'Verify Your Email',
	SETUP_PASSWORD: 'Setup Your Password'
};
  
CONSTANTS.EMAIL_CONTENTS = {
  
	RESET_PASSWORD_EMAIL: 'public/templates/resetPasswordEmail.html',
	RESET_PASSWORD_TEMPLATE: '../public/templates/reset-password.html',
	SETUP_PASSWORD_EMAIL_TEMPLATE: 'public/templates/setup-password-email.html',
	SETUP_PASSWORD_TEMPLATE: '../public/templates/setup-password.html',
	RESET_PASSWORD_LINK_EXPIRED_TEMPLATE: '../public/templates/password-link-expired.html',
	EMAIL_VERIFICATION_TEMPLATE: 'public/templates/verify-admin-email.html',
	EMAIL_VERIFIED_SUCCESSFULLY_TEMPLATE: '../public/templates/verified-email-successfully.html',
	SOMETHING_WENT_WRONG_TEMPLATE: '../public/templates/something-went-wrong.html'
};


CONSTANTS.AVAILABLE_EXTENSIONS_FOR_FILE_UPLOADS = [ 'csv', 'png', 'jpeg', 'svg', 'jpg', 'mp4', 'x-m4v', 'webm', 'mov', 'svg', 'xls', 'xlsx', 'pdf' ];
CONSTANTS.ALLOWED_EXTENSIONS_FOR_PROFILE_IMAGE = [ 'jpg', 'png', 'jpeg', 'JPG', 'PNG', 'JPEG', 'webp', 'WEBP' ];

CONSTANTS.GENDER = {
	MALE: 'Male',
	FEMALE: 'Female',
	OTHERS: 'Other',
};

CONSTANTS.OTP_EXPIRIED_TIME_IN_SECONDS = 300;

CONSTANTS.OTP_EXPIRY_TIME = 5; // minutes

CONSTANTS.S3_DEFAULT_IMAGE = 'default.png';

CONSTANTS.REDIS_EXPIRE_TIME_IN_SEC = 10800;

CONSTANTS.SOCKET_EVENTS = {
	TEST: 'test',
	DISCONNECT: 'disconnect',
};

CONSTANTS.PAGINATION = {
	SKIP: 0,
	LIMIT: 10,
};

CONSTANTS.REDIS_EVENTS = {
	TEST: 'test',
};

CONSTANTS.CONTENT_TYPE = {
	HEADERS: 1,
	ETHEREUM_DESCRIPTIONS: 2,
	VIDEO_DETAILS: 3,
	PRIZE_SECTION: 4,
	WINNER_LIST: 5,
	WINNER_DETAILS: 6,
	CONTRACT_DETAILS: 7,
	ROADMAP: 8,
	FEATURED_DETAILS: 9,
	TOKEN_INFO: 10,
	EXTERNAL_AUDIT: 11,
	PREMIUM_MARKETPLACE: 12,
	FOOTERS: 13,
	AIRDROP: 14,
	PARTNERS: 15,
};

CONSTANTS.TX_TYPE = {
	MINT: 1,
	TRANSFER: 2,
	MINT_TRANSFER: 3
};

CONSTANTS.EVENT_TYPE = {
	MINT: 'mint',
	TRANSFER: 'transfer',
	MINT_TRANSFER: 'mintAndTransfer'
};


CONSTANTS.TX_STATUS = {
	PENDING: 'pending',
	SUCCESS: 'success',
	FAILURE: 'failure'
};

// used while minting
CONSTANTS.GENESIS_ADDRESS = '0x0000000000000000000000000000000000000000';

CONSTANTS.USER_PRIZE_TYPE = {
	CAR: 1,
	TOKEN: 2
};
CONSTANTS.RESULT_TYPE = {
	MANUAL: 1,
	AUTOMATIC: 2
};

CONSTANTS.WINNER_PRIZE_UPDATE_TIME_LIMIT_DAYS = 7;

CONSTANTS.MATHEMATICAL = {
	MILLISECONDS_IN_A_DAY: 86400000 // 24 * 60 * 60 * 1000
};

CONSTANTS.SIGNATURE_MESSAGE = 'fasdkfjklandfkdsfjladsfodfafjalfadsfkads';

CONSTANTS.SEEDS = {
	MASTER: 'master'
};

CONSTANTS.DEFAULT_LOTTERY_START_VALUE = 10000000;

CONSTANTS.FILES_WITH_CUSTOM_CONTENT_TYPES = {
	'svg': 'image/svg+xml',
	'mp4': 'video/mp4',
	'webm': 'video/webm',
	'mov': 'video/quicktime',
};

CONSTANTS.WALLET_ADDRESS_MAPPING = {
	'0x1D4E75975416DA8d715Cb69A78F04E373b5f5750': 'd07a48dc00e870b8a24705172f628c21f09d4abe95a42e5ce576b54039def18a',
	'0x02a76888d59760610e60124cab4267b17736182d': 'e38c618924dad8598453e8a95afc759b661b805a082b41e5be8c95e766b2d0fa',
	'0xF346A628822aE957103737490E99d8d1DBA8144d': 'f76777d5fa5ec345af3c098f510c3c843e8aeb45ad66731f2647170fd0e52f62',
};


CONSTANTS.LANGUAGES = {
	ENGLISH: 'EN',
	FINNISH: 'FI'
};

module.exports = CONSTANTS;
